version: "3.9"
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: "${HOPS_DB_USERNAME}"
      POSTGRES_PASSWORD: "${HOPS_DB_PASSWORD}"
      POSTGRES_DB: "${HOPS_DB_NAME}"
    volumes:
      - ${HOPS_DB_DATA}:/var/lib/postgresql/data
  envoy:
    image: envoyproxy/envoy-dev:b8f85f43b90d69b9e7303d68d1ea585f723759d0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    links:
      - api
    depends_on:
      - api
    ports:
      - 3001:9393
  api:
    image: registry.hopsoffice.com/hops-api:latest
    links:
      - db
    depends_on:
      - db
    environment:
      DB_USERNAME: "${HOPS_DB_USERNAME}"
      DB_PASSWORD: "${HOPS_DB_PASSWORD}"
      DB_HOST: "db:5432"
      DB_NAME: "${HOPS_DB_NAME}"
      HOPS_GOOGLE_APP_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      HOPS_GOOGLE_APP_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      HOPS_LICENSE_ID: "${HOPS_LICENSE_ID}"
      HOPS_ON_PREMISES_INITIAL_USER_EMAIL: "${HOPS_INITIAL_USER_EMAIL}"
      HOPS_ON_PREMISES_USER_PASSWORD_DEFAULT: "${HOPS_DEFAULT_USER_PASSWORD}"
      JWT_SECRET: "${HOPS_SECRET_KEY}"
  oauth:
    image: registry.hopsoffice.com/hops-oauth:latest
    environment:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
    ports:
      - 3002:2608
  frontend:
    image: registry.hopsoffice.com/hops-frontend:latest
    environment:
      API_URL: "http://${HOPS_DEPLOY_DOMAIN}:3001"
      OAUTH_URL: "http://${HOPS_DEPLOY_DOMAIN}:3002"
    ports:
      - 3000:3000
    depends_on:
      - envoy
      - oauth
