version: "3.9"
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: "${HOPS_DB_USERNAME}"
      POSTGRES_PASSWORD: "${HOPS_DB_PASSWORD}"
      POSTGRES_DB: "${HOPS_DB_NAME}"
    volumes:
      - ${HOPS_DB_DATA}:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13.1
  envoy:
    image: envoyproxy/envoy-dev:b8f85f43b90d69b9e7303d68d1ea585f723759d0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    links:
      - api
    depends_on:
      - api
    ports:
      - 3001:9393
  api:
    image: registry.hopsoffice.com/hops-api:latest
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    environment:
      CLOUD_GCP_CREDENTIALS_JSON: |
        {
          "type": "service_account",
          "project_id": "",
          "private_key_id": "",
          "private_key": "-----BEGIN PRIVATE KEY-----\nMIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEA7M+LPMAp/X2ApOOJ\nV6PAZUA39T8HJ0ojQXdEVjD+6EjnuC0o/nxXopRdrSFbjkP4GiQoyxQ7VeXqHpK3\nfMN0twIDAQABAkBQ8Yv1QvXXWIudUM0EMMu1kCLQaC/IxTWRzfOExpCK0qA6ZFKz\n2a36GYH79519uwTMJD9FBH5TiUWGpSiGmpmRAiEA/3KqtHpaqYYnq9yURYm/AiXA\n8Jo+7D2Mq5U66QN2MHkCIQDtUpDI6/xEQWOKLTy90sdUMzUFx08pln8DaJ3bzTpi\nrwIgWJiikBnnm+hFlhvY6Q1PTCVf95Lnw/PM+C230t06frECIQCpEQjUGkm81lhz\nN4buNBqMgW5kj3h1yCDz7LOIwsu1QQIgKBFKLWrJdhuqIIYGcj8FXL4gbCdOUY+x\nDJLSCivLnDk=\n-----END PRIVATE KEY-----",
          "client_email": "",
          "client_id": "",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/example%40example.com",
          "universe_domain": "googleapis.com"
        }
      CLOUD_GCP_PROJECT_ID: "example-12345"
      CLOUD_GCP_PROJECT_NUMBER: "123456"
      CLOUD_GCP_REGION: "asia-northeast3"
      DB_USERNAME: "${HOPS_DB_USERNAME}"
      DB_PASSWORD: "${HOPS_DB_PASSWORD}"
      DB_HOST: "db:5432"
      DB_NAME: "${HOPS_DB_NAME}"
      HOPS_GOOGLE_APP_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      HOPS_GOOGLE_APP_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      HOPS_LICENSE_ID: "${HOPS_LICENSE_ID}"
      HOPS_ON_PREMISES_INITIAL_USER_EMAIL: "${HOPS_INITIAL_USER_EMAIL}"
      HOPS_ON_PREMISES_USER_PASSWORD_DEFAULT: "${HOPS_DEFAULT_USER_PASSWORD}"
      JWT_SECRET: "${HOPS_SECRET_KEY}"
      SPRING_RABBITMQ_ADDRESSES: "amqp://guest:guest@rabbitmq//"
      SPRING_DATASOURCE_USER_URL: "jdbc:postgresql://${HOPS_DB_USERNAME}:${HOPS_DB_PASSWORD}@:db:5432/${HOPS_DB_USERNAME}"
      JAVA_OPTS: "-XX:MaxDirectMemorySize=256M"
  oauth:
    image: registry.hopsoffice.com/hops-oauth:latest
    environment:
      SERVER_FORWARD_HEADERS_STRATEGY: "FRAMEWORK"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      SERVER_TOMCAT_INTERNAL_PROXIES: ".*"
      SERVER_USE_FORWARD_HEADERS: true
    ports:
      - 3002:2608
  frontend:
    image: registry.hopsoffice.com/hops-frontend:latest
    environment:
      API_URL: "http://${HOPS_DEPLOY_DOMAIN}:3001"
      OAUTH_URL: "http://${HOPS_DEPLOY_DOMAIN}:3002"
    ports:
      - 3000:3000
    depends_on:
      - envoy
      - oauth
