services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: "${HOPS_DB_USERNAME}"
      POSTGRES_PASSWORD: "${HOPS_DB_PASSWORD}"
      POSTGRES_DB: "${HOPS_DB_NAME}"
    volumes:
      - ${HOPS_DB_DATA}:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13.1
  envoy:
    image: envoyproxy/envoy-dev:b8f85f43b90d69b9e7303d68d1ea585f723759d0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    links:
      - api
    depends_on:
      - api
    ports:
      - 3001:9393
  api:
    image: registry.hopsoffice.com/hops-api:latest
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/${HOPS_DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${HOPS_DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${HOPS_DB_PASSWORD}"
      HOPS_GOOGLE_APP_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      HOPS_GOOGLE_APP_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      HOPS_LICENSE_ID: "${HOPS_LICENSE_ID}"
      HOPS_ON_PREMISES_INITIAL_USER_EMAIL: "${HOPS_INITIAL_USER_EMAIL}"
      HOPS_ON_PREMISES_USER_PASSWORD_DEFAULT: "${HOPS_DEFAULT_USER_PASSWORD}"
      JWT_SECRET: "${HOPS_SECRET_KEY}"
      SPRING_RABBITMQ_ADDRESSES: "amqp://guest:guest@rabbitmq//"
      SPRING_DATASOURCE_USER_URL: "jdbc:postgresql://${HOPS_DB_USERNAME}:${HOPS_DB_PASSWORD}@:db:5432/${HOPS_DB_USERNAME}"
      JAVA_OPTS: "-XX:MaxDirectMemorySize=256M"
  oauth:
    image: registry.hopsoffice.com/hops-oauth:latest
    environment:
      SERVER_FORWARD_HEADERS_STRATEGY: "FRAMEWORK"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SLACK_CLIENT_ID: "${SLACK_CLIENT_ID}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SLACK_CLIENT_SECRET: "${SLACK_CLIENT_SECRET}"
      SERVER_TOMCAT_INTERNAL_PROXIES: ".*"
      SERVER_USE_FORWARD_HEADERS: true
    ports:
      - 3002:2608
  frontend:
    image: registry.hopsoffice.com/hops-frontend:latest
    environment:
      API_URL: "http://${HOPS_DEPLOY_DOMAIN}:3001"
      OAUTH_URL: "http://${HOPS_DEPLOY_DOMAIN}:3002"
    ports:
      - 3000:3000
    depends_on:
      - envoy
      - oauth
