{{- $name := print .Release.Name "-" $.Values.environment "-" "web" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ $name }}
  name: {{ $name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - image: "{{ .Values.registryUrl }}/{{ .Values.api.repo.name }}{{- if .Values.api.repo.tag -}}
          :{{ .Values.api.repo.tag }}
        {{- else if .Values.api.repo.hash -}}
          @sha256:{{ .Values.api.repo.hash }}
        {{- end }}"
          imagePullPolicy: Always
          name: {{ $name }}
          ports:
            - name: grpc
              containerPort: {{ .Values.api.grpc.port }}
            - name: http
              containerPort: {{ .Values.api.http.port }}
          env:
            {{- range .Values.api.secrets }}
            - name: {{ . | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretsName }}
                  key: {{ . }}
            {{- end }}
            {{- with .Values.api.environments }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
            - name: JAVA_OPTS
              value: "-XX:MaxDirectMemorySize=256M"
            - name: GRPC_PORT
              value: {{ .Values.api.grpc.port | quote }}
            - name: SERVER_PORT
              value: {{ .Values.api.http.port | quote }}
          resources:
            requests:
              memory: {{ .Values.api.memory.requests }}
            limits:
              memory: {{ .Values.api.memory.limits }}
          startupProbe:
            grpc:
              port: {{ .Values.api.grpc.port }}
            initialDelaySeconds: 30
            periodSeconds: 1
            failureThreshold: 90
          livenessProbe:
            grpc:
              port: {{ .Values.api.grpc.port }}
            periodSeconds: 5
            failureThreshold: 3
          {{- with .Values.api.volumeMounts }}
            {{ toYaml . | nindent 10 }}
          {{- end }}
        - name: envoy
          image: {{ .Values.api.envoy.repo }}
          ports:
            - name: envoy
              containerPort: 10000
          volumeMounts:
            - name: {{ $name }}-envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
          readinessProbe:
            httpGet:
              path: /readyz
              port: 10000
            initialDelaySeconds: 30
            periodSeconds: 1
            failureThreshold: 90
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: {{ $name }}-envoy-config
          configMap:
            name: {{ $name }}-envoy-config
        {{- with .Values.api.volumeMounts }}
          {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ $name }}
  name: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 10000
