{{- $name := print .Release.Name "-" .Values.environment "-" "frontend" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ $name }}
  name: {{ $name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - image: "{{ .Values.registryUrl }}/{{ .Values.frontend.repo.name }}{{- if .Values.frontend.repo.tag -}}
          :{{ .Values.frontend.repo.tag }}
        {{- else if .Values.frontend.repo.hash -}}
          @sha256:{{ .Values.frontend.repo.hash }}
        {{- end }}"
          imagePullPolicy: Always
          name: {{ $name }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            {{- with .Values.frontend.environments }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
            - name: API_URL
              value: "//{{ .Values.api.host }}"
            - name: OAUTH_URL
              value: "//{{ .Values.oauth.host }}"
          resources:
            requests:
              memory: {{ .Values.frontend.memory.requests }}
            limits:
              memory: {{ .Values.frontend.memory.limits }}
          startupProbe:
            httpGet:
              path: "/"
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 1
            failureThreshold: 25
          livenessProbe:
            httpGet:
              path: "/"
              port: {{ .Values.frontend.port }}
            periodSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: regcred
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ $name }}
  name: {{ $name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.frontend.port }}
