environment: local
registryUrl: registry.hopsoffice.com
secretsName: hops-secrets
serviceAccountName:

api:
  replicaCount: 1
  host: hops-api
  repo:
    name: hops-api
    hash: null
    tag: latest
  environments:
  nodeSelector: {}
  grpc:
    port: 2607
  http:
    port: 2610
  envoy:
    repo: envoyproxy/envoy:v1.29-latest
    port: 10000
  secrets:
    - cloud_gcp_project_id
    - cloud_gcp_project_number
    - cloud_gcp_region
    - cloud_gcp_credentials_json

    - hops_google_app_client_id
    - hops_google_app_client_secret
    - hops_license_id
    - hops_license_proxy_url
    - hops_on_premises_initial_user_email
    - hops_on_premises_user_password_default

    - jwt_secret

    - spring_datasource_username
    - spring_datasource_password
    - spring_datasource_url

    - spring_datasource_user_password
    - spring_datasource_user_url
    - spring_datasource_user_username

    - spring_rabbitmq_addresses

    - spring_ssl_bundle_jks_primary_keystore_location
    - spring_ssl_bundle_jks_primary_keystore_password
  volumeMounts:

oauth:
  replicaCount: 1
  host: hops-oauth
  port: 2608
  repo:
    name: hops-oauth
    hash: null
    tag: latest
  environments:
  nodeSelector:
  secrets:
    - spring_security_oauth2_client_registration_google_client_id
    - spring_security_oauth2_client_registration_google_client_secret
    - spring_security_oauth2_client_registration_slack_client_id
    - spring_security_oauth2_client_registration_slack_client_secret

frontend:
  replicaCount: 1
  host: hops-frontend
  port: 3000
  repo:
    name: hops-frontend
    hash: null
    tag: latest
  environments:
  nodeSelector:
